// Database types for Supabase client
// This file should be generated by Supabase CLI, but we're creating it manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      offices: {
        Row: {
          id: string;
          broker_id: string | null;
          name: string;
          address: string | null;
          city: string | null;
          state: string | null;
          zip_code: string | null;
          phone: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          broker_id?: string | null;
          name: string;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          phone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          broker_id?: string | null;
          name?: string;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          phone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          email: string;
          role: 'admin' | 'broker' | 'agent';
          office_id: string | null;
          broker_id: string | null;
          first_name: string | null;
          last_name: string | null;
          phone: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          role?: 'admin' | 'broker' | 'agent';
          office_id?: string | null;
          broker_id?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          role?: 'admin' | 'broker' | 'agent';
          office_id?: string | null;
          broker_id?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      leads: {
        Row: {
          id: string;
          user_id: string;
          office_id: string | null;
          first_name: string;
          last_name: string;
          email: string | null;
          phone: string | null;
          budget_min: number | null;
          budget_max: number | null;
          property_type: 'single_family' | 'condo' | 'townhouse' | 'land' | 'multi_family' | 'commercial' | null;
          location_preference: string | null;
          lead_source: 'website' | 'referral' | 'cold_call' | 'email' | 'social_media' | 'mls' | 'other';
          status: 'new' | 'prospecting' | 'nurturing' | 'under_contract' | 'closed' | 'lost';
          score: number;
          next_follow_up: string | null;
          last_contact_at: string | null;
          stage_changed_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          office_id?: string | null;
          first_name: string;
          last_name: string;
          email?: string | null;
          phone?: string | null;
          budget_min?: number | null;
          budget_max?: number | null;
          property_type?: 'single_family' | 'condo' | 'townhouse' | 'land' | 'multi_family' | 'commercial' | null;
          location_preference?: string | null;
          lead_source?: 'website' | 'referral' | 'cold_call' | 'email' | 'social_media' | 'mls' | 'other';
          status?: 'new' | 'prospecting' | 'nurturing' | 'under_contract' | 'closed' | 'lost';
          score?: number;
          next_follow_up?: string | null;
          last_contact_at?: string | null;
          stage_changed_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          office_id?: string | null;
          first_name?: string;
          last_name?: string;
          email?: string | null;
          phone?: string | null;
          budget_min?: number | null;
          budget_max?: number | null;
          property_type?: 'single_family' | 'condo' | 'townhouse' | 'land' | 'multi_family' | 'commercial' | null;
          location_preference?: string | null;
          lead_source?: 'website' | 'referral' | 'cold_call' | 'email' | 'social_media' | 'mls' | 'other';
          status?: 'new' | 'prospecting' | 'nurturing' | 'under_contract' | 'closed' | 'lost';
          score?: number;
          next_follow_up?: string | null;
          last_contact_at?: string | null;
          stage_changed_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      properties: {
        Row: {
          id: string;
          mls_id: string | null;
          user_id: string | null;
          office_id: string | null;
          address: string;
          city: string;
          state: string;
          zip_code: string;
          latitude: number | null;
          longitude: number | null;
          price: number | null;
          bed_count: number | null;
          bath_count: number | null;
          sqft: number | null;
          lot_size: number | null;
          year_built: number | null;
          property_type: 'single_family' | 'condo' | 'townhouse' | 'land' | 'multi_family' | 'commercial' | null;
          status: 'active' | 'pending' | 'sold' | 'off_market';
          description: string | null;
          list_date: string | null;
          sold_date: string | null;
          days_on_market: number;
          is_mls: boolean;
          source_system: string | null;
          last_synced_at: string | null;
          raw_mls_data: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          mls_id?: string | null;
          user_id?: string | null;
          office_id?: string | null;
          address: string;
          city: string;
          state: string;
          zip_code: string;
          latitude?: number | null;
          longitude?: number | null;
          price?: number | null;
          bed_count?: number | null;
          bath_count?: number | null;
          sqft?: number | null;
          lot_size?: number | null;
          year_built?: number | null;
          property_type?: 'single_family' | 'condo' | 'townhouse' | 'land' | 'multi_family' | 'commercial' | null;
          status?: 'active' | 'pending' | 'sold' | 'off_market';
          description?: string | null;
          list_date?: string | null;
          sold_date?: string | null;
          days_on_market?: number;
          is_mls?: boolean;
          source_system?: string | null;
          last_synced_at?: string | null;
          raw_mls_data?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          mls_id?: string | null;
          user_id?: string | null;
          office_id?: string | null;
          address?: string;
          city?: string;
          state?: string;
          zip_code?: string;
          latitude?: number | null;
          longitude?: number | null;
          price?: number | null;
          bed_count?: number | null;
          bath_count?: number | null;
          sqft?: number | null;
          lot_size?: number | null;
          year_built?: number | null;
          property_type?: 'single_family' | 'condo' | 'townhouse' | 'land' | 'multi_family' | 'commercial' | null;
          status?: 'active' | 'pending' | 'sold' | 'off_market';
          description?: string | null;
          list_date?: string | null;
          sold_date?: string | null;
          days_on_market?: number;
          is_mls?: boolean;
          source_system?: string | null;
          last_synced_at?: string | null;
          raw_mls_data?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      interactions: {
        Row: {
          id: string;
          lead_id: string;
          user_id: string;
          type: 'call' | 'email' | 'meeting' | 'note' | 'sms';
          description: string;
          duration_minutes: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          user_id: string;
          type: 'call' | 'email' | 'meeting' | 'note' | 'sms';
          description: string;
          duration_minutes?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          lead_id?: string;
          user_id?: string;
          type?: 'call' | 'email' | 'meeting' | 'note' | 'sms';
          description?: string;
          duration_minutes?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      lead_properties: {
        Row: {
          id: string;
          lead_id: string;
          property_id: string;
          interaction_type: string | null;
          view_count: number;
          last_viewed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          property_id: string;
          interaction_type?: string | null;
          view_count?: number;
          last_viewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          lead_id?: string;
          property_id?: string;
          interaction_type?: string | null;
          view_count?: number;
          last_viewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      tasks: {
        Row: {
          id: string;
          user_id: string;
          assigned_to_user_id: string | null;
          lead_id: string | null;
          property_id: string | null;
          title: string;
          description: string | null;
          due_date: string | null;
          priority: 'low' | 'medium' | 'high';
          status: 'new' | 'in_progress' | 'completed';
          is_recurring: boolean;
          recurrence_rule: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          assigned_to_user_id?: string | null;
          lead_id?: string | null;
          property_id?: string | null;
          title: string;
          description?: string | null;
          due_date?: string | null;
          priority?: 'low' | 'medium' | 'high';
          status?: 'new' | 'in_progress' | 'completed';
          is_recurring?: boolean;
          recurrence_rule?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          assigned_to_user_id?: string | null;
          lead_id?: string | null;
          property_id?: string | null;
          title?: string;
          description?: string | null;
          due_date?: string | null;
          priority?: 'low' | 'medium' | 'high';
          status?: 'new' | 'in_progress' | 'completed';
          is_recurring?: boolean;
          recurrence_rule?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      calendar_events: {
        Row: {
          id: string;
          user_id: string;
          event_type: 'showing' | 'meeting' | 'open_house' | 'blocked_time';
          title: string;
          description: string | null;
          start_time: string;
          end_time: string;
          location: string | null;
          property_id: string | null;
          attendees: Json | null;
          external_calendar_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          event_type: 'showing' | 'meeting' | 'open_house' | 'blocked_time';
          title: string;
          description?: string | null;
          start_time: string;
          end_time: string;
          location?: string | null;
          property_id?: string | null;
          attendees?: Json | null;
          external_calendar_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          event_type?: 'showing' | 'meeting' | 'open_house' | 'blocked_time';
          title?: string;
          description?: string | null;
          start_time?: string;
          end_time?: string;
          location?: string | null;
          property_id?: string | null;
          attendees?: Json | null;
          external_calendar_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      communications: {
        Row: {
          id: string;
          user_id: string;
          lead_id: string | null;
          type: 'email' | 'sms' | 'internal_message';
          direction: 'inbound' | 'outbound';
          subject: string | null;
          body: string | null;
          recipient: string | null;
          recipient_email: string | null;
          recipient_phone: string | null;
          status: 'draft' | 'sent' | 'delivered' | 'failed';
          read_at: string | null;
          is_replied: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          lead_id?: string | null;
          type: 'email' | 'sms' | 'internal_message';
          direction: 'inbound' | 'outbound';
          subject?: string | null;
          body?: string | null;
          recipient?: string | null;
          recipient_email?: string | null;
          recipient_phone?: string | null;
          status?: 'draft' | 'sent' | 'delivered' | 'failed';
          read_at?: string | null;
          is_replied?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          lead_id?: string | null;
          type?: 'email' | 'sms' | 'internal_message';
          direction?: 'inbound' | 'outbound';
          subject?: string | null;
          body?: string | null;
          recipient?: string | null;
          recipient_email?: string | null;
          recipient_phone?: string | null;
          status?: 'draft' | 'sent' | 'delivered' | 'failed';
          read_at?: string | null;
          is_replied?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      lead_imports: {
        Row: {
          id: string;
          user_id: string;
          office_id: string | null;
          file_name: string;
          total_rows: number;
          successful_rows: number;
          failed_rows: number;
          duplicate_rows: number;
          status: 'processing' | 'completed' | 'failed';
          error_details: Json | null;
          started_at: string;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          office_id?: string | null;
          file_name: string;
          total_rows?: number;
          successful_rows?: number;
          failed_rows?: number;
          duplicate_rows?: number;
          status?: 'processing' | 'completed' | 'failed';
          error_details?: Json | null;
          started_at?: string;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          office_id?: string | null;
          file_name?: string;
          total_rows?: number;
          successful_rows?: number;
          failed_rows?: number;
          duplicate_rows?: number;
          status?: 'processing' | 'completed' | 'failed';
          error_details?: Json | null;
          started_at?: string;
          completed_at?: string | null;
          created_at?: string;
        };
      };
      audit_log: {
        Row: {
          id: string;
          user_id: string | null;
          action: 'create' | 'update' | 'delete' | 'view' | 'export';
          resource_type: string;
          resource_id: string;
          old_values: Json | null;
          new_values: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          status: 'success' | 'failure';
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          action: 'create' | 'update' | 'delete' | 'view' | 'export';
          resource_type: string;
          resource_id: string;
          old_values?: Json | null;
          new_values?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          status?: 'success' | 'failure';
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          action?: 'create' | 'update' | 'delete' | 'view' | 'export';
          resource_type?: string;
          resource_id?: string;
          old_values?: Json | null;
          new_values?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          status?: 'success' | 'failure';
          created_at?: string;
        };
      };
      mls_listings: {
        Row: {
          id: string;
          property_id: string | null;
          mls_id: string;
          source_system: string;
          raw_data: Json;
          synced_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          property_id?: string | null;
          mls_id: string;
          source_system: string;
          raw_data: Json;
          synced_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          property_id?: string | null;
          mls_id?: string;
          source_system?: string;
          raw_data?: Json;
          synced_at?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Functions: {
      // Add function definitions here if needed
    };
  };
}